More action commands, view server configs, and mod log error logs
MirageAegis/Sushi-Bot pull request #45
Opened 2023-09-22 18:13 UTC by MirageAegis

# What Does This PR Do?
This PR adds more action commands for users to use, a command for server administrators to view their server configurations, and error logs for moderation log errors. Sushi Bot's version will be increased to 2.1.0 with this PR.

## Acceptance Criteria Met
- Sushi Bot has a command that displays server configurations to server administrators.
- Sushi Bot has a `/kiss` command that works similarly to `/bonk`.
- Sushi Bot has a `/bite` command that works similarly to `/bonk`.
- Sushi Bot has a `/roll` command that lets users roll 1~10 dice with 2~1000 sides.
- Moderation logs' try-catch blocks have been moved to the `logTo` calls.
- User update embeds should no longer error out because of empty strings.

## Related Issues
Closes #42 
Closes #43 
Closes #44

2023-09-22 18:49 UTC, MirageAegis reviewed
This review will walk though all noteworthy changes in this PR.

2023-09-22 18:49 UTC, MirageAegis commented on src/commands/action/bite.ts
> +};
This is the `/bite` command. It and the `/kiss` command are the new action commands that are similar to the existing action commands.

2023-09-22 18:49 UTC, MirageAegis commented on src/commands/action/bonk.ts
> +        const gif: string = await tenor.getGifs("bonk");
The amine search word has been moved to the `getGifs` method of the `TenorSingleton`.

2023-09-22 18:49 UTC, MirageAegis commented on src/commands/action/roll.ts
> +};
This is the `/roll` command, which lets users roll 1~10 2~1000 sided dice.

2023-09-22 18:49 UTC, MirageAegis commented on src/commands/configuration/config-subcommands/view.ts
> +export const command: Subcommand = {
This is the `/config view` command that displays server configurations to server administrators.

2023-09-22 18:49 UTC, MirageAegis commented on src/events/events.ts
> +    }
All `try-catch` blocks for moderation logs have been moved to the `logTo` calls of each moderation log handler.

2023-09-22 18:49 UTC, MirageAegis commented on src/events/events.ts
> +    }
The message logs handlers have also been updated to ignore the bot's own messages.

2023-09-22 18:49 UTC, MirageAegis commented on src/events/events.ts
> +    }
This section has been added to the presence update handler to avoid having partial user data.

2023-09-22 18:49 UTC, MirageAegis commented on src/util/tenor-utils.ts
> +            q: "anime " + topic, // Prepend every query with "anime " to only receive anime gifs
Anime is being prepended to every query, so all queries result in anime gifs.

2023-09-27 18:38 UTC, ZacAndrei commented on src/commands/action/pat.ts
> +        const gif: string = await tenor.getGifs("anime headpat");
didn't you move anime out of the topics or smth?

2023-09-27 19:03 UTC, ZacAndrei requested changes
little typo

2023-09-28 06:09 UTC, ZacAndrei approved these changes

2023-09-28 06:09 UTC, merged